name: Cache query compilation
description: Caches CodeQL compilation caches - should be run both on PRs and pushes to main.

inputs:
  key:
    description: 'The cache key to use - should be unique to the workflow'
    required: true

outputs:
  cache-dir:
    description: "The directory where the cache was stored"
    value: ${{ steps.fill-compilation-dir.outputs.compdir }}

runs:
  using: composite
  steps:
    - name: Cache the query compilation caches
      uses: ./.github/actions/incremental-cache
      with:
        path: '**/.cache'
        key: codeql-compile-${{ inputs.key }}
    - name: Fill compilation cache directory
      id: fill-compilation-dir
      shell: bash
      run: |
        # Move all the existing cache into another folder, so we only preserve the cache for the current queries.
        node $GITHUB_WORKSPACE/.github/actions/cache-query-compilation/move-caches.js ${COMBINED_CACHE_DIR}

        echo "compdir=${COMBINED_CACHE_DIR}" >> $GITHUB_OUTPUT
      env:
        COMBINED_CACHE_DIR: ${{ runner.temp }}/compilation-dir
