name: Run Swift quick tests
description: Runs Swift tests defined in Bazel. Must be run after `setup-env`
runs:
  using: composite
  steps:
    - name: Run xcode-autobuilder tests
      if: runner.os == 'macOS'
      shell: bash
      run: |
        bazel test //swift/xcode-autobuilder/tests
    - name: Run codegen tests
      shell: bash
      run: |
        bazel test //swift/codegen/test
    - name: Run qltest tests
      shell: bash
      run: |
        bazel test //swift/tools/test/qltest
