name: Build Swift CodeQL pack
description: Builds the Swift CodeQL pack
inputs:
  flags:
    description: "Additional `codeql test run` flags"
    required: false
    default: ""
runs:
  using: composite
  steps:
    - uses: ./swift/actions/share-extractor-pack
    - uses: ./.github/actions/fetch-codeql
    - name: Run QL tests
      shell: bash
      run: |
        codeql test run \
          --threads=0 \
          --ram 5000 \
          --search-path "${{ github.workspace }}/swift/extractor-pack" \
          --check-databases \
          --check-unused-labels \
          --check-repeated-labels \
          --check-redefined-labels \
          --check-use-before-definition \
          ${{ inputs.flags }} \
          swift/ql/test
      env:
        GITHUB_TOKEN: ${{ github.token }}
