name: Setup Swift Package Environment
description: Sets up the environment in which to build the Swift package and run its tests
runs:
  using: composite
  steps:
    - uses: bazelbuild/setup-bazelisk@v2
    - uses: actions/setup-python@v4
      with:
        python-version-file: 'swift/.python-version'
    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: "~/.cache/bazel-repository-cache"
        key: bazel-cache-${{ runner.os }}-${{ runner.arch }}
    - name: Mount bazel disk cache
      uses: actions/cache@v3
      with:
        path: "~/.cache/bazel-disk-cache"
        key: bazel-disk-cache-${{ runner.os }}-${{ runner.arch }}
    - name: Set up bazel disk cache
      shell: bash
      run: |
        echo build --repository_cache=~/.cache/bazel-repository-cache --disk_cache=~/.cache/bazel-disk-cache > ~/.bazelrc
        echo test --test_output=errors >> ~/.bazelrc
