name: Sync Main
on:
  pull_request:
    branches:
      - "main" 
  schedule:
    - cron:  '* * * * *'
  workflow_dispatch:
jobs:
  sync-main:
    name: Sync-main
    runs-on: ubuntu-latest
    if: github.repository == 'microsoft/codeql'
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Git config
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Fetch
        shell: bash
        run: |
          set -x
          git fetch
          git remote add upstream https://github.com/github/codeql.git
          git fetch upstream

      - name: Sync Main
        shell: bash
        run: |
          git checkout --track origin/main
          git merge --no-edit upstream/main
          git push origin main
